Repository codeit-2000/codeit-resources, pull requests merged in 2024-10, with the labels that each got.

#14 📦 Chore(#11): ES lint, prettier 세팅
  .husky/pre-commit
  .prettierrc.json
  apps/mobile/.eslintrc.js
  apps/mobile/package.json
  apps/web/.eslintrc.mjs
  apps/web/eslint.config.js
  apps/web/package.json
  apps/web/src/App.tsx
  package.json
  pnpm-lock.yaml
Labels: 📦️ Chore

#8 📦 Chore(#2): storybook 적용 및 chromatic 배포
  .github/workflows/storybook.yml
  apps/web/.gitignore
  apps/web/.storybook/main.ts
  apps/web/.storybook/preview.ts
  apps/web/package.json
  apps/web/src/components/Button/index.css
  apps/web/src/components/Button/index.stories.tsx
  apps/web/src/components/Button/index.tsx
  apps/web/src/stories/intro.mdx
  apps/web/src/stories/palette.mdx
  apps/web/src/stories/typography.mdx
  apps/web/tsconfig.app.json
  apps/web/vite.config.ts
  package.json
  packages/ui/package.json
  packages/ui/src/Button/index.css
  packages/ui/src/Button/index.stories.tsx
  packages/ui/src/Button/index.tsx
  packages/ui/src/button.tsx
  packages/ui/src/card.tsx
  packages/ui/src/code.tsx
  pnpm-lock.yaml
Labels: 📦️ Chore, 🚀 Deploy

#15 📦 Chore(#12): 프로젝트 기본 세팅 (라이브러리 설치 및 라우팅)
  apps/web/.eslintrc.mjs
  apps/web/package.json
  apps/web/src/App.css
  apps/web/src/App.tsx
  apps/web/src/components/layout/Sidebar/index.tsx
  apps/web/src/components/layout/index.tsx
  apps/web/src/pages/dashboard/index.tsx
  apps/web/src/pages/equipments/index.tsx
  apps/web/src/pages/meeting-rooms/index.tsx
  apps/web/src/pages/seats/index.tsx
  apps/web/src/styles/ResetCss.tsx
  apps/web/tsconfig.app.json
  apps/web/vite.config.ts
  pnpm-lock.yaml
Labels: 📦️ Chore, 🌐 Web

#16 📦 Chore(#13): amplify setting
  amplify.yml
  apps/mobile/App.tsx
  apps/web/package.json
  apps/web/src/App.tsx
  apps/web/src/main.tsx
  apps/web/src/pages/amplify-test/index.tsx
  packages/shared-backend/.gitignore
  packages/shared-backend/amplify/auth/resource.ts
  packages/shared-backend/amplify/backend.ts
  packages/shared-backend/amplify/data/resource.ts
  packages/shared-backend/amplify/package.json
  packages/shared-backend/amplify/tsconfig.json
  packages/shared-backend/package.json
  pnpm-lock.yaml
Labels: 📦️ Chore

#19 📦 Chore(#17): husky setting
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  package.json
Labels: 📦️ Chore

#23 📦 Chore(#18): PR review github action 추가
  .github/workflows/review_assign.yml
Labels: 📦️ Chore

#24 📦 Chore(#21): 타입스크립트 다운그레이드 및 typescript-estree 오류 해결
  apps/mobile/package.json
  package.json
  packages/eslint-config/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: 📦️ Chore, 🌐 Web

#28 📦️ Chore(#20): SVGR 및 폰트 세팅
  apps/web/index.html
  apps/web/package.json
  apps/web/src/App.tsx
  apps/web/src/assets/icons/logo.svg
  apps/web/src/components/layout/Sidebar/index.tsx
  apps/web/src/index.css
  apps/web/src/main.tsx
  apps/web/src/styles/ResetCss.tsx
  apps/web/src/vite-env.d.ts
  apps/web/vite.config.ts
  pnpm-lock.yaml
Labels: 📦️ Chore, 🌐 Web

#32 Chore(#27): tailwind css 세팅
  .github/workflows/review_assign.yml
  apps/web/package.json
  apps/web/postcss.config.cjs
  apps/web/src/App.css
  apps/web/src/App.tsx
  apps/web/src/components/layout/Sidebar/index.tsx
  apps/web/src/components/layout/index.tsx
  apps/web/src/index.css
  apps/web/tailwind.config.js
  pnpm-lock.yaml
Labels: 📦️ Chore

#35 🐛 Fix: expo 실행 에러
  apps/web/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: 🚑️ Fix

#40 📦 Chore: add tag
  packages/shared-backend/amplify/backend.ts
Labels: 📦️ Chore

#43 ✨ Feat: 네이게이션 바 컴포넌트 구현
  .prettierrc.json
  apps/web/package.json
  apps/web/src/components/layout/NavigationBar/NavOptionList.tsx
  apps/web/src/components/layout/NavigationBar/Sidebar.tsx
  apps/web/src/components/layout/Sidebar/index.tsx
  apps/web/src/components/layout/index.tsx
  apps/web/src/hooks/useDeviceSize.ts
  apps/web/tailwind.config.js
  packages/shared-assets/icons/icon-equipment.svg
  packages/shared-assets/icons/icon-meeting.svg
  packages/shared-assets/icons/icon-person.svg
  packages/shared-assets/icons/icon-seats.svg
  packages/shared-assets/images/codeit-resources.svg
  pnpm-lock.yaml
Labels: ✨ Feat, 🌐 Web

#44 📦 Chore(#42): color 팔레트 상수 파일로 추가 및 tailwind 컬러 세팅
  apps/web/package.json
  apps/web/tailwind.config.ts
  packages/shared-constants/constants/colors.js
  packages/shared-constants/package.json
  pnpm-lock.yaml
Labels: 📦️ Chore, 🌐 Web

#45 ✨ Feat(#38): resource schema
  apps/web/src/pages/amplify-test/index.tsx
  packages/shared-backend/amplify/data/resource.ts
Labels: ✨ Feat, 💻 Server

#48 ✨ Feat(#22): 예약 스키마 추가 및 기본 함수 추가
  apps/web/package.json
  packages/shared-backend/amplify/data/resource.ts
  packages/shared-lib/api/reservation.ts
  packages/shared-lib/package.json
  pnpm-lock.yaml
Labels: ✨ Feat, 💻 Server

#52 ✨ Feat(#9): 전역 디바이스 사이즈 계산 훅 네비게이션 바에 적용
  apps/web/src/App.tsx
  apps/web/src/components/layout/MobileSizeWatcher/index.tsx
  apps/web/src/components/layout/NavigationBar/NavOptionList.tsx
  apps/web/src/components/layout/NavigationBar/index.stories.tsx
  apps/web/src/components/layout/NavigationBar/index.tsx
  apps/web/src/components/layout/index.tsx
  apps/web/src/hooks/useIsMobile.ts
  apps/web/src/store/mobileAtom.ts
  apps/web/tsconfig.app.json
  package.json
  pnpm-lock.yaml
Labels: 💄 Design, ✨ Feat

#57 ✨ Feat(#49): Resource CRUD API 함수
  packages/shared-backend/amplify/data/resource.ts
  packages/shared-lib/api/resource.ts
  packages/shared-lib/package.json
  pnpm-lock.yaml
Labels: ✨ Feat, 💻 Server

#60 ♻️ Refactor(#59): Layout & Navbar
  apps/web/src/App.tsx
  apps/web/src/Router.tsx
  apps/web/src/components/layout/NavigationBar/index.tsx
  apps/web/src/components/layout/index.tsx
Labels: 🔨 Refactor

#54 ✨ Feat(#50): 공통 Badge 컴포넌트
  apps/web/src/components/commons/Badge/index.stories.tsx
  apps/web/src/components/commons/Badge/index.tsx
  apps/web/tailwind.config.ts
Labels: ✨ Feat, 🌐 Web

#64 🐛 Fix(#63): lint 적용 안 되는 문제
  .prettierrc.json
  apps/web/.eslintrc.json
  apps/web/.eslintrc.mjs
  apps/web/package.json
  apps/web/src/App.tsx
  apps/web/src/components/commons/Badge/index.stories.tsx
  apps/web/src/components/commons/Badge/index.tsx
  apps/web/src/components/commons/Button/index.tsx
  apps/web/src/components/layout/MobileSizeWatcher/index.tsx
  apps/web/src/components/layout/NavigationBar/Sidebar.tsx
  apps/web/src/components/layout/NavigationBar/index.tsx
  apps/web/src/main.tsx
  apps/web/src/store/mobileAtom.ts
  apps/web/tsconfig.app.json
  package.json
  packages/shared-backend/amplify/data/resource.ts
  pnpm-lock.yaml
Labels: 🚑️ Fix

#61 ✨ Feat(#6): Global Modal System
  apps/web/src/App.tsx
  apps/web/src/components/commons/Button/index.stories.tsx
  apps/web/src/components/commons/Button/index.tsx
  apps/web/src/components/commons/Modal/MoveSeatConfirmModal.tsx
  apps/web/src/components/commons/Modal/index.stories.tsx
  apps/web/src/components/commons/Modal/index.tsx
  apps/web/src/hooks/useModal.ts
  apps/web/src/store/modalAtom.ts
  pnpm-lock.yaml
Labels: ✨ Feat, 🌐 Web

#58 ✅ Test(#56): 간단하게 로그인/회원가입 구현
  apps/web/src/Router.tsx
  apps/web/src/pages/auth-test/index.tsx
  apps/web/src/utils/autoAuthUser.ts
  package.json
  packages/shared-backend/amplify/auth/resource.ts
  pnpm-lock.yaml
Labels: 💻 Server

#65 ✨ Feat(#30): Profile Image 컴포넌트
  apps/web/src/components/commons/ProfileImage/index.stories.tsx
  apps/web/src/components/commons/ProfileImage/index.tsx
  packages/shared-lib/api/resource.ts
Labels: ✨ Feat

#67 ✨ Feat(#7): 라디오 공통 컴포넌트 제작
  apps/web/src/components/commons/Radio/index.stories.tsx
  apps/web/src/components/commons/Radio/index.tsx
Labels: ✨ Feat, 🌐 Web

#69 ✨ Feat(#68): splash screen 화면 추가 및 nav, 기본구조 설정
  apps/mobile/app.json
  apps/mobile/app/(tabs)/_layout.tsx
  apps/mobile/app/(tabs)/dashboard.tsx
  apps/mobile/app/(tabs)/equipments.tsx
  apps/mobile/app/(tabs)/meeting-rooms.tsx
  apps/mobile/app/(tabs)/seats.tsx
  apps/mobile/app/_layout.tsx
  apps/mobile/app/index.tsx
  apps/mobile/assets/adaptive-icon.png
  apps/mobile/assets/codeit-splash.png
  apps/mobile/assets/codeit.png
  apps/mobile/assets/favicon.png
  apps/mobile/assets/icon.png
  apps/mobile/assets/splash.png
  apps/mobile/babel.config.js
  apps/mobile/declarations.d.ts
  apps/mobile/metro.config.js
  apps/mobile/package.json
  apps/mobile/tsconfig.json
  apps/web/src/components/layout/NavigationBar/Sidebar.tsx
  apps/web/src/components/layout/NavigationBar/index.tsx
  packages/shared-assets/icons/icon-equipment.svg
  packages/shared-assets/icons/icon-meeting.svg
  packages/shared-assets/icons/icon-person.svg
  packages/shared-assets/icons/icon-seats.svg
  packages/shared-assets/images/codeit-resources.svg
  pnpm-lock.yaml
Labels: ✨ Feat, 📱 Mobile

#70 ✨ Feat(#31): Input 공통 컴포넌트 제작
  apps/web/src/components/commons/Input/index.stories.tsx
  apps/web/src/components/commons/Input/index.tsx
  apps/web/src/index.css
  apps/web/tailwind.config.ts
  packages/shared-constants/constants/colors.js
  pnpm-lock.yaml
Labels: ✨ Feat, 🌐 Web

#77 ✨ Feat(#76): Resource 테이블 권한 설정
  packages/shared-backend/amplify/data/resource.ts
Labels: ✨ Feat, 💻 Server

#62 ✨ Feat(#5): toast 공통 컴포넌트 구현
  apps/web/src/App.tsx
  apps/web/src/components/commons/Toast/ToastProvider.tsx
  apps/web/src/components/commons/Toast/index.stories.tsx
  apps/web/src/components/commons/Toast/index.tsx
  apps/web/src/components/layout/index.tsx
  apps/web/src/hooks/useToast.ts
  apps/web/src/store/toastAtom.ts
Labels: 💄 Design, ✨ Feat

#79 ✨ Feat(#78): 예약 수정,삭제,생성시 로직 추가
  apps/web/src/components/layout/NavigationBar/NavOptionList.tsx
  packages/shared-backend/amplify/data/createReservationHandler/handler.ts
  packages/shared-backend/amplify/data/deleteReservationHandler/handler.ts
  packages/shared-backend/amplify/data/resource.ts
  packages/shared-backend/amplify/data/updateReservationHandler/handler.ts
  packages/shared-lib/api/reservation.ts
Labels: ✨ Feat, 💻 Server

#81 🐛 Fix: 중복 import 제거
  apps/web/src/App.tsx
Labels: 🚑️ Fix

#71 ✨ feat: user 관련 api 작성
  packages/shared-backend/amplify/data/resource.ts
  packages/shared-lib/api/user.ts
Labels: ✨ Feat, 💻 Server

#86 ✨ Feat(#72): 공용 탭 컴포넌트
  apps/web/src/components/commons/Tab/index.stories.tsx
  apps/web/src/components/commons/Tab/index.tsx
  apps/web/src/components/commons/Tab/useTabDrag.ts
  apps/web/src/index.css
Labels: ✨ Feat

#88 ✨ Feat(#87): 좌석 페이지 UI
  apps/web/src/components/layout/NavigationBar/index.tsx
  apps/web/src/pages/seats/Error.tsx
  apps/web/src/pages/seats/Header.tsx
  apps/web/src/pages/seats/Loading.tsx
  apps/web/src/pages/seats/SeatButton.tsx
  apps/web/src/pages/seats/SeatGrid.tsx
  apps/web/src/pages/seats/index.tsx
Labels: 💄 Design, ✨ Feat

#83 ✨ Feat(#53): 모바일 바텀시트, 데스크탑 드로워 구현
  apps/web/package.json
  apps/web/src/components/commons/BottomSheet/BackgroundOverlay.tsx
  apps/web/src/components/commons/BottomSheet/BottomSheetOpenButton.tsx
  apps/web/src/components/commons/BottomSheet/index.stories.tsx
  apps/web/src/components/commons/BottomSheet/index.tsx
  apps/web/src/components/commons/Drawer/index.stories.tsx
  apps/web/src/components/commons/Drawer/index.tsx
  packages/shared-assets/icons/icon-double-right-arrow.svg
  packages/shared-assets/icons/icon-drawer-bar.svg
  pnpm-lock.yaml
Labels: 💄 Design, ✨ Feat

#92 📦 Chore: Tanstack Query 기본 세팅
  apps/web/package.json
  apps/web/src/App.tsx
  apps/web/src/pages/auth-test/index.tsx
  pnpm-lock.yaml
Labels: 📦️ Chore

#97 🐛 fix(#96): 빌드 오류 수정
  apps/web/src/components/commons/BottomSheet/index.tsx
Labels: 🚑️ Fix

#94 ✨ Feat(#51): 공통 Dropdown 컴포넌트 개발
  apps/web/src/components/commons/Dropdown/Toggle/MeetingRoomToggle.tsx
  apps/web/src/components/commons/Dropdown/Toggle/OrderToggle.tsx
  apps/web/src/components/commons/Dropdown/Toggle/RoleToggle.tsx
  apps/web/src/components/commons/Dropdown/Toggle/TimeToggle.tsx
  apps/web/src/components/commons/Dropdown/index.stories.tsx
  apps/web/src/components/commons/Dropdown/index.tsx
  apps/web/tailwind.config.ts
  packages/shared-assets/icons/icon-arrow-down.svg
  packages/shared-assets/icons/icon-check.svg
  packages/shared-assets/icons/icon-order.svg
  packages/shared-constants/constants/dropdownConstants.ts
Labels: ✨ Feat, 🌐 Web

#104 ✨ Feat(#101): ListItem 컴포넌트 구현
  apps/web/src/components/commons/Input/index.tsx
  apps/web/src/components/commons/ListItem/components/Right.tsx
  apps/web/src/components/commons/ListItem/components/Title.tsx
  apps/web/src/components/commons/ListItem/index.stories.tsx
  apps/web/src/components/commons/ListItem/index.tsx
  apps/web/src/index.css
  packages/shared-assets/icons/icon-hamburger.svg
Labels: ✨ Feat, 🌐 Web

#106 ✨ Feat(#105): 팀 관리 페이지 팀 추가 UI 및 기능 구현
  apps/web/src/components/commons/Modal/MoveSeatConfirmModal.tsx
  apps/web/src/components/commons/Modal/index.stories.tsx
  apps/web/src/components/commons/Modal/index.tsx
  apps/web/src/hooks/useModal.ts
  apps/web/src/pages/admin/team/components/AddTeamModal.tsx
  apps/web/src/pages/admin/team/components/TeamList.tsx
  apps/web/src/pages/admin/team/index.tsx
  packages/shared-backend/amplify/data/resource.ts
  packages/shared-lib/api/team.ts
  packages/shared-lib/zod-schema/team.tsx
Labels: ✨ Feat, 🌐 Web

#102 ♻️ Refactor(#100): subtype에 맞게 쿼리할 수 있도록 함수 업데이트
  apps/web/src/pages/seats/SeatGrid.tsx
  packages/shared-backend/amplify/data/resource.ts
  packages/shared-lib/api/resource.ts
Labels: 🔨 Refactor

#107 ✨ Feat(#95): 타임라인 UI 구현
  apps/web/src/components/TimeLine/ThirtyMinutesTimeBox.tsx
  apps/web/src/components/TimeLine/TimeHeader.tsx
  apps/web/src/components/TimeLine/TimeLine.tsx
  apps/web/src/components/TimeLine/TimeLinetypes.ts
  apps/web/src/components/TimeLine/TimeText.tsx
  apps/web/src/utils/createTime.ts
Labels: 💄 Design, ✨ Feat

#111 ✨ Feat(#73): 회의실 예약 페이지 기본 컴포넌트 제작
  apps/web/src/components/commons/Banner/index.stories.tsx
  apps/web/src/components/commons/Banner/index.tsx
  apps/web/src/components/commons/Input/index.tsx
  apps/web/src/components/commons/ListItem/index.tsx
  apps/web/src/pages/meeting-rooms/Layout.tsx
  apps/web/src/pages/meeting-rooms/ReservationForm.tsx
  apps/web/src/pages/meeting-rooms/RoomSelection.tsx
  apps/web/src/pages/meeting-rooms/index.tsx
  packages/shared-constants/constants/timeSlot.ts
  packages/shared-lib/package.json
  packages/shared-lib/utils/getDaysUntilEndOfMonth.ts
  packages/shared-lib/utils/timeUtils.ts
  packages/shared-lib/zod-schema/reservation.ts
Labels: ✨ Feat, 🌐 Web

#118 🐛 Fix: 빌드 에러 설정 변경
  apps/web/tsconfig.app.json
Labels: 📦️ Chore

#122 🔨Refactor(#120): reservation 스키마수정
  apps/web/src/components/commons/Input/index.tsx
  packages/shared-backend/amplify/data/resource.ts
Labels: 🌐 Web, 💻 Server
